package com.sotti.milliscope.design.system

import androidx.compose.ui.graphics.Color

internal object ColorTokens {
    internal object Light {
        internal object StandardContrast {
            internal val primary = Color(color = 0xFF0057D1)
            internal val onPrimary = Color(color = 0xFFFFFFFF)
            internal val primaryContainer = Color(color = 0xFFD4E3FF)
            internal val onPrimaryContainer = Color(color = 0xFF001A3C)
            internal val secondary = Color(color = 0xFF7453FF)
            internal val onSecondary = Color(color = 0xFFFFFFFF)
            internal val secondaryContainer = Color(color = 0xFFE7DFFF)
            internal val onSecondaryContainer = Color(color = 0xFF21005C)
            internal val tertiary = Color(color = 0xFF00B6D6)
            internal val onTertiary = Color(color = 0xFFFFFFFF)
            internal val tertiaryContainer = Color(color = 0xFFC8F7FF)
            internal val onTertiaryContainer = Color(color = 0xFF00363D)
            internal val error = Color(color = 0xFFCE2B2B)
            internal val onError = Color(color = 0xFFFFFFFF)
            internal val errorContainer = Color(color = 0xFFFFDAD4)
            internal val onErrorContainer = Color(color = 0xFF410002)
            internal val background = Color(color = 0xFFF7F9FE)
            internal val onBackground = Color(color = 0xFF171C23)
            internal val surface = Color(color = 0xFFF7F9FE)
            internal val onSurface = Color(color = 0xFF171C23)
            internal val surfaceVariant = Color(color = 0xFFDCE3F2)
            internal val onSurfaceVariant = Color(color = 0xFF44474E)
            internal val outline = Color(color = 0xFF5D6B80)
            internal val outlineVariant = Color(color = 0xFFC7D0E1)
            internal val scrim = Color(color = 0xFF000000)
            internal val inverseSurface = Color(color = 0xFF27324A)
            internal val inverseOnSurface = Color(color = 0xFFEFF2FA)
            internal val inversePrimary = Color(color = 0xFFB4CDFF)
            internal val surfaceDim = Color(color = 0xFFD9E2F3)
            internal val surfaceBright = Color(color = 0xFFF7F9FE)
            internal val surfaceContainerLowest = Color(color = 0xFFFFFFFF)
            internal val surfaceContainerLow = Color(color = 0xFFF2F6FD)
            internal val surfaceContainer = Color(color = 0xFFECF2FA)
            internal val surfaceContainerHigh = Color(color = 0xFFE6EDFA)
            internal val surfaceContainerHighest = Color(color = 0xFFE2E9F7)
        }
    }

    internal object Dark {
        internal object StandardContrast {
            internal val primary = Color(color = 0xFF8AC1FF)
            internal val onPrimary = Color(color = 0xFF00204B)
            internal val primaryContainer = Color(color = 0xFF003B78)
            internal val onPrimaryContainer = Color(color = 0xFFC6E2FF)
            internal val secondary = Color(color = 0xFFC0A7FF)
            internal val onSecondary = Color(color = 0xFF301A67)
            internal val secondaryContainer = Color(color = 0xFF7453FF)
            internal val onSecondaryContainer = Color(color = 0xFFE7DFFF)
            internal val tertiary = Color(color = 0xFF40EFFF)
            internal val onTertiary = Color(color = 0xFF00363D)
            internal val tertiaryContainer = Color(color = 0xFF005564)
            internal val onTertiaryContainer = Color(color = 0xFFC8F7FF)
            internal val error = Color(color = 0xFFFFB3AB)
            internal val onError = Color(color = 0xFF60151A)
            internal val errorContainer = Color(color = 0xFFCE2B2B)
            internal val onErrorContainer = Color(color = 0xFFFFDAD4)
            internal val background = Color(color = 0xFF131A23)
            internal val onBackground = Color(color = 0xFFDDE9F9)
            internal val surface = Color(color = 0xFF131A23)
            internal val onSurface = Color(color = 0xFFDDE9F9)
            internal val surfaceVariant = Color(color = 0xFF38445B)
            internal val onSurfaceVariant = Color(color = 0xFFB7C7E6)
            internal val outline = Color(color = 0xFF8193B6)
            internal val outlineVariant = Color(color = 0xFF364A6B)
            internal val scrim = Color(color = 0xFF000000)
            internal val inverseSurface = Color(color = 0xFFDDE9F9)
            internal val inverseOnSurface = Color(color = 0xFF16213A)
            internal val inversePrimary = Color(color = 0xFF3A91F7)
            internal val surfaceDim = Color(color = 0xFF1B263A)
            internal val surfaceBright = Color(color = 0xFF28355A)
            internal val surfaceContainerLowest = Color(color = 0xFF101624)
            internal val surfaceContainerLow = Color(color = 0xFF18202F)
            internal val surfaceContainer = Color(color = 0xFF1B263A)
            internal val surfaceContainerHigh = Color(color = 0xFF232E45)
            internal val surfaceContainerHighest = Color(color = 0xFF2A3754)
        }
    }
}