package com.sottti.milliscope.design.system

import androidx.compose.ui.graphics.Color

internal object ColorTokens {
    internal object Light {
        internal object StandardContrast {
            internal val primary = Color(0xFF0057D1)
            internal val onPrimary = Color(0xFFFFFFFF)
            internal val primaryContainer = Color(0xFFD4E3FF)
            internal val onPrimaryContainer = Color(0xFF001A3C)
            internal val secondary = Color(0xFF7453FF)
            internal val onSecondary = Color(0xFFFFFFFF)
            internal val secondaryContainer = Color(0xFFE7DFFF)
            internal val onSecondaryContainer = Color(0xFF21005C)
            internal val tertiary = Color(0xFF00B6D6)
            internal val onTertiary = Color(0xFFFFFFFF)
            internal val tertiaryContainer = Color(0xFFC8F7FF)
            internal val onTertiaryContainer = Color(0xFF00363D)
            internal val error = Color(0xFFCE2B2B)
            internal val onError = Color(0xFFFFFFFF)
            internal val errorContainer = Color(0xFFFFDAD4)
            internal val onErrorContainer = Color(0xFF410002)
            internal val background = Color(0xFFF7F9FE)
            internal val onBackground = Color(0xFF171C23)
            internal val surface = Color(0xFFF7F9FE)
            internal val onSurface = Color(0xFF171C23)
            internal val surfaceVariant = Color(0xFFDCE3F2)
            internal val onSurfaceVariant = Color(0xFF44474E)
            internal val outline = Color(0xFF5D6B80)
            internal val outlineVariant = Color(0xFFC7D0E1)
            internal val scrim = Color(0xFF000000)
            internal val inverseSurface = Color(0xFF27324A)
            internal val inverseOnSurface = Color(0xFFEFF2FA)
            internal val inversePrimary = Color(0xFFB4CDFF)
            internal val surfaceDim = Color(0xFFD9E2F3)
            internal val surfaceBright = Color(0xFFF7F9FE)
            internal val surfaceContainerLowest = Color(0xFFFFFFFF)
            internal val surfaceContainerLow = Color(0xFFF2F6FD)
            internal val surfaceContainer = Color(0xFFECF2FA)
            internal val surfaceContainerHigh = Color(0xFFE6EDFA)
            internal val surfaceContainerHighest = Color(0xFFE2E9F7)
        }
    }

    internal object Dark {
        internal object StandardContrast {
            internal val primary = Color(0xFF8AC1FF)
            internal val onPrimary = Color(0xFF00204B)
            internal val primaryContainer = Color(0xFF003B78)
            internal val onPrimaryContainer = Color(0xFFC6E2FF)
            internal val secondary = Color(0xFFC0A7FF)
            internal val onSecondary = Color(0xFF301A67)
            internal val secondaryContainer = Color(0xFF7453FF)
            internal val onSecondaryContainer = Color(0xFFE7DFFF)
            internal val tertiary = Color(0xFF40EFFF)
            internal val onTertiary = Color(0xFF00363D)
            internal val tertiaryContainer = Color(0xFF005564)
            internal val onTertiaryContainer = Color(0xFFC8F7FF)
            internal val error = Color(0xFFFFB3AB)
            internal val onError = Color(0xFF60151A)
            internal val errorContainer = Color(0xFFCE2B2B)
            internal val onErrorContainer = Color(0xFFFFDAD4)
            internal val background = Color(0xFF131A23)
            internal val onBackground = Color(0xFFDDE9F9)
            internal val surface = Color(0xFF131A23)
            internal val onSurface = Color(0xFFDDE9F9)
            internal val surfaceVariant = Color(0xFF38445B)
            internal val onSurfaceVariant = Color(0xFFB7C7E6)
            internal val outline = Color(0xFF8193B6)
            internal val outlineVariant = Color(0xFF364A6B)
            internal val scrim = Color(0xFF000000)
            internal val inverseSurface = Color(0xFFDDE9F9)
            internal val inverseOnSurface = Color(0xFF16213A)
            internal val inversePrimary = Color(0xFF3A91F7)
            internal val surfaceDim = Color(0xFF1B263A)
            internal val surfaceBright = Color(0xFF28355A)
            internal val surfaceContainerLowest = Color(0xFF101624)
            internal val surfaceContainerLow = Color(0xFF18202F)
            internal val surfaceContainer = Color(0xFF1B263A)
            internal val surfaceContainerHigh = Color(0xFF232E45)
            internal val surfaceContainerHighest = Color(0xFF2A3754)
        }
    }
}
